config/routes.rb
Rails.application.routes.draw do
  resources :colegiados
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :filas
  resources :mesas
  resources :rodadas
  resources :vagas
  resources :alunos

  root to: "tela#home"
  
  # # Used by e2e tests (in another project):
  # get "/reset", to: "tela#reset", as: :reset
  # get "/cria-cenario", to: "tela#cria_cenario", as: :cria_cenario

  get "/tela", to: "tela#index", as: :tela
  get "/tela/dados", to: "tela#dados", as: :tela_dados
  post "/tela/inscrever", to: "tela#inscrever", as: :tela_inscrever

  post "/mesas/:id/escolher", to: "mesas#escolher", as: :mesa_escolher
  post "/mesas/remover-selecao", to: "mesas#remover_selecao", as: :mesa_remover_selecao

  put "/filas/:id/proximo", to: "filas#proximo", as: :filas_proximo
  put "/filas/:id/anterior", to: "filas#anterior", as: :filas_anterior
  put "/filas/:id/esvazia_mesa", to: "filas#esvazia_mesa", as: :esvazia_mesa
  get "/filas/:id/shuffle", to: "filas#shuffle", as: :shuffle

  put "/colegiados/:id/proximo", to: "colegiados#proximo", as: :colegiados_proximo
  put "/colegiados/:id/anterior", to: "colegiados#anterior", as: :colegiados_anterior
  put "/colegiados/:id/esvazia_mesa", to: "colegiados#esvazia_mesa", as: :colegiado_esvazia_mesa

  get "/posicao/:matricula", to: "tela#posicao_aluno"

  get "/importar", to: "importer#index"
  post "/importar", to: "importer#import"

  get "/inscricao", to: "inscricao#index"
  post "/inscricao", to: "inscricao#inscrever"

  devise_for :users, controllers: { registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/colegiado.rb
class Colegiado < ApplicationRecord
  has_many :alunos
  has_many :filas

  def proxima_fila_nao_vazia
    self.filas.order(prioridade: :asc).each do |fila|
      if fila.posicao < fila.vagas.count
        return fila
      end
    end
    return nil
  end

  def title
    "#{self.nome}"
  end
end

app/controllers/colegiados_controller.rb
class ColegiadosController < ApplicationController
  before_action :set_colegiado, only: [:show, :edit, :update, :destroy, :proximo, :anterior, :esvazia_mesa]
  load_and_authorize_resource
  
  # GET /colegiados
  # GET /colegiados.json
  def index
    @colegiados = Colegiado.all
  end

  # GET /colegiados/1
  # GET /colegiados/1.json
  def show
    # @vaga = @fila.vaga_atual
    @mesa_atual = Mesa.find_by id: session[:mesa]
    @vaga = @mesa_atual.vaga if @mesa_atual
  end

  # GET /colegiados/new
  def new
    @colegiado = Colegiado.new
  end

  # GET /colegiados/1/edit
  def edit
  end

  # POST /colegiados
  # POST /colegiados.json
  def create
    @colegiado = Colegiado.new(colegiado_params)

    respond_to do |format|
      if @colegiado.save
        format.html { redirect_to @colegiado, notice: 'Colegiado was successfully created.' }
        format.json { render :show, status: :created, location: @colegiado }
      else
        format.html { render :new }
        format.json { render json: @colegiado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colegiados/1
  # PATCH/PUT /colegiados/1.json
  def update
    respond_to do |format|
      if @colegiado.update(colegiado_params)
        format.html { redirect_to @colegiado, notice: 'Colegiado was successfully updated.' }
        format.json { render :show, status: :ok, location: @colegiado }
      else
        format.html { render :edit }
        format.json { render json: @colegiado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colegiados/1
  # DELETE /colegiados/1.json
  def destroy
    @colegiado.destroy
    respond_to do |format|
      format.html { redirect_to colegiados_url, notice: 'Colegiado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def anterior
    raise Exception, "Not implemented"
  end

  def proximo
    if !session[:mesa]
      return redirect_to @colegiado, notice: 'É preciso selecionar uma mesa antes.'
    end
    mesa_atual = Mesa.find_by id: session[:mesa]
    if !mesa_atual
      return redirect_to @colegiado, notice: 'É preciso selecionar uma mesa antes.'
    end
    @fila = @colegiado.proxima_fila_nao_vazia
    if @fila
      if @fila.posicao == @fila.vagas.count && session[:mesa]
        if not mesa_atual.esta_vazia?
          Mesa.associa_vaga_a_mesa(nil, session[:mesa])
          notifica
        end
      else
        @fila.chama_proximo(session[:mesa], 1)
        notifica
      end
    else
      if not mesa_atual.esta_vazia?
        Mesa.associa_vaga_a_mesa(nil, session[:mesa])
        notifica
      end
    end

    redirect_to @colegiado
  end

  def esvazia_mesa
    Mesa.associa_vaga_a_mesa(nil, session[:mesa])
    notifica
    redirect_to @colegiado
  end

  private

    def notifica
      ActionCable.server.broadcast 'telao_notifications_channel', Rodada.dados
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_colegiado
      @colegiado = Colegiado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colegiado_params
      params.require(:colegiado).permit(:nome, :codigo)
    end
end

app/helpers/colegiados_helper.rb
module ColegiadosHelper
end

app/views/colegiados/_form.html.erb
<%= form_with(model: colegiado, local: true) do |form| %>
  <% if colegiado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(colegiado.errors.count, "error") %> prohibited this colegiado from being saved:</h2>

      <ul>
      <% colegiado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/colegiados/edit.html.erb
<h1>Editing Colegiado</h1>

<%= render 'form', colegiado: @colegiado %>

<%= link_to 'Show', @colegiado %> |
<%= link_to 'Back', colegiados_path %>

app/views/colegiados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colegiados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Codigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colegiados.each do |colegiado| %>
      <tr>
        <td><%= colegiado.nome %></td>
        <td><%= colegiado.codigo %></td>
        <td><%= link_to 'Show', colegiado %></td>
        <td><%= link_to 'Edit', edit_colegiado_path(colegiado) %></td>
        <td><%= link_to 'Destroy', colegiado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Colegiado', new_colegiado_path %>

app/views/colegiados/new.html.erb
<h1>New Colegiado</h1>

<%= render 'form', colegiado: @colegiado %>

<%= link_to 'Back', colegiados_path %>

app/views/colegiados/show.html.erb
<script type="text/javascript">
  // https://notificationsounds.com/notification-sounds/pull-out-551
  var audioNotificacao = new Audio('/pull-out.mp3');

  function notificSobreNovoAluno(data) {
    audioNotificacao.play();
    toastr.info("" + data.aluno.nome + " acabou de entrar na fila.");
  }

  function trataInscricao(data) {
    if (data.fila.colegiado.id == <%= @colegiado.id %> && <%= @vaga.nil? ? "true" : "false" %>) {
      notificSobreNovoAluno(data);
    }
  }
</script>

<h1><%= @colegiado.nome %></h1>

<p id="notice"><%= notice %></p>

<p>
  Mesa atual: <b><%= @mesa_atual.nome if @mesa_atual %></b> <%= link_to 'alterar', mesas_path %>
</p>

<p>
  <strong>Aluno na mesa:</strong>
  <span style="color: blue;"><%= @vaga&.posicao %> <%= @vaga&.aluno&.title %> - <%= @vaga&.codigo %></span>
  <% if @vaga %>
    <%= link_to 'Desvincular', colegiado_esvazia_mesa_path, method: :put %>
  <% end %>
</p>

<br>

<div>
  <%# link_to 'Anterior', colegiados_anterior_path(@colegiado), method: :put %>
  <%= link_to 'Chama próximo', colegiados_proximo_path(@colegiado), method: :put, class: 'button' %>
</div>

<br><br><br>

<%= link_to 'Edit', edit_colegiado_path(@colegiado) %> |
<%= link_to 'Back', colegiados_path %>


<script type="text/javascript">
document.addEventListener("turbolinks:load", function () {

  if (<%= @vaga.nil? ? "true" : "false" %>) {
    App.room = App.cable.subscriptions.create("InscricaoChannel", {
      received: trataInscricao
    });
  }

  // para testar no rails console:
  // InscricaoChannel.inscreve({aluno: {nome: 'Fulano de Tal'}, fila: {colegiado: {id: 1}}})
});
</script>