config/routes.rb
Rails.application.routes.draw do
  resources :colegiados
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :filas
  resources :mesas
  resources :rodadas
  resources :vagas
  resources :alunos

  root to: "tela#home"
  
  # # Used by e2e tests (in another project):
  # get "/reset", to: "tela#reset", as: :reset
  # get "/cria-cenario", to: "tela#cria_cenario", as: :cria_cenario

  get "/tela", to: "tela#index", as: :tela
  get "/tela/dados", to: "tela#dados", as: :tela_dados
  post "/tela/inscrever", to: "tela#inscrever", as: :tela_inscrever

  post "/mesas/:id/escolher", to: "mesas#escolher", as: :mesa_escolher
  post "/mesas/remover-selecao", to: "mesas#remover_selecao", as: :mesa_remover_selecao

  put "/filas/:id/proximo", to: "filas#proximo", as: :filas_proximo
  put "/filas/:id/anterior", to: "filas#anterior", as: :filas_anterior
  put "/filas/:id/esvazia_mesa", to: "filas#esvazia_mesa", as: :esvazia_mesa
  get "/filas/:id/shuffle", to: "filas#shuffle", as: :shuffle

  put "/colegiados/:id/proximo", to: "colegiados#proximo", as: :colegiados_proximo
  put "/colegiados/:id/anterior", to: "colegiados#anterior", as: :colegiados_anterior
  put "/colegiados/:id/esvazia_mesa", to: "colegiados#esvazia_mesa", as: :colegiado_esvazia_mesa

  get "/posicao/:matricula", to: "tela#posicao_aluno"

  get "/importar", to: "importer#index"
  post "/importar", to: "importer#import"

  get "/inscricao", to: "inscricao#index"
  post "/inscricao", to: "inscricao#inscrever"

  devise_for :users, controllers: { registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mesa.rb
class Mesa < ApplicationRecord
  belongs_to :vaga, required: false

  def self.associa_vaga_a_mesa(vaga, id_mesa)
    mesa_atual = Mesa.find_by id: id_mesa
    if mesa_atual
      mesa_atual.update(vaga: vaga)
    end
  end

  def esta_vazia?
    self.vaga.nil?
  end

  def title
    "#{self.nome}"
  end
end

app/controllers/mesas_controller.rb
class MesasController < ApplicationController
  before_action :set_mesa, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /mesas
  # GET /mesas.json
  def index
    @mesas = Mesa.all
    @mesa_atual = Mesa.find_by id: session[:mesa] if session[:mesa]
  end

  # GET /mesas/1
  # GET /mesas/1.json
  def show
  end

  # GET /mesas/new
  def new
    @mesa = Mesa.new
  end

  # GET /mesas/1/edit
  def edit
  end

  def remover_selecao
    session[:mesa] = params[:id]
    redirect_to mesas_path
  end

  def escolher
    session[:mesa] = params[:id]
    redirect_to mesas_path
  end

  # POST /mesas
  # POST /mesas.json
  def create
    @mesa = Mesa.new(mesa_params)

    respond_to do |format|
      if @mesa.save
        format.html { redirect_to @mesa, notice: 'Mesa was successfully created.' }
        format.json { render :show, status: :created, location: @mesa }
      else
        format.html { render :new }
        format.json { render json: @mesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mesas/1
  # PATCH/PUT /mesas/1.json
  def update
    respond_to do |format|
      if @mesa.update(mesa_params)
        format.html { redirect_to @mesa, notice: 'Mesa was successfully updated.' }
        format.json { render :show, status: :ok, location: @mesa }
      else
        format.html { render :edit }
        format.json { render json: @mesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mesas/1
  # DELETE /mesas/1.json
  def destroy
    @mesa.destroy
    respond_to do |format|
      format.html { redirect_to mesas_url, notice: 'Mesa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mesa
      @mesa = Mesa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mesa_params
      params.require(:mesa).permit(:nome, :ativo, :aluno_id)
    end
end

app/helpers/mesas_helper.rb
module MesasHelper
end

app/views/mesas/_form.html.erb
<%= form_with(model: mesa, local: true) do |form| %>
  <% if mesa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mesa.errors.count, "error") %> prohibited this mesa from being saved:</h2>

      <ul>
      <% mesa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :ativo %>
    <%= form.check_box :ativo %>
  </div>

  <div class="field">
    <%= form.label :vaga_id %>
    <%= form.text_field :vaga_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mesas/edit.html.erb
<h1>Editing Mesa</h1>

<%= render 'form', mesa: @mesa %>

<%= link_to 'Show', @mesa %> |
<%= link_to 'Back', mesas_path %>

app/views/mesas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mesas</h1>

<p>
  Mesa escolhida: <b><%= @mesa_atual.nome if @mesa_atual %></b>
  <% if @mesa_atual %>
    <%= link_to 'Remover seleção', mesa_remover_selecao_path, method: :post %>
  <% end %>
</p>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Ativo</th>
      <th>Aluno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mesas.each do |mesa| %>
      <tr>
        <td><%= mesa.nome %></td>
        <td><%= mesa.ativo %></td>
        <td><%= mesa.vaga.aluno if mesa.vaga %></td>
        <td><%= link_to 'Escolher', mesa_escolher_path(mesa), method: :post %></td>
        <td><%= link_to 'Show', mesa %></td>
        <td><%= link_to 'Edit', edit_mesa_path(mesa) %></td>
        <td><%= link_to 'Destroy', mesa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mesa', new_mesa_path %>

app/views/mesas/new.html.erb
<h1>New Mesa</h1>

<%= render 'form', mesa: @mesa %>

<%= link_to 'Back', mesas_path %>

app/views/mesas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @mesa.nome %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @mesa.ativo %>
</p>

<p>
  <strong>Aluno:</strong>
  <%= @mesa.vaga.aluno if @mesa.vaga %>
</p>

<%= link_to 'Edit', edit_mesa_path(@mesa) %> |
<%= link_to 'Back', mesas_path %>