config/routes.rb
Rails.application.routes.draw do
  resources :colegiados
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :filas
  resources :mesas
  resources :rodadas
  resources :vagas
  resources :alunos

  root to: "tela#home"
  
  # # Used by e2e tests (in another project):
  # get "/reset", to: "tela#reset", as: :reset
  # get "/cria-cenario", to: "tela#cria_cenario", as: :cria_cenario

  get "/tela", to: "tela#index", as: :tela
  get "/tela/dados", to: "tela#dados", as: :tela_dados
  post "/tela/inscrever", to: "tela#inscrever", as: :tela_inscrever

  post "/mesas/:id/escolher", to: "mesas#escolher", as: :mesa_escolher
  post "/mesas/remover-selecao", to: "mesas#remover_selecao", as: :mesa_remover_selecao

  put "/filas/:id/proximo", to: "filas#proximo", as: :filas_proximo
  put "/filas/:id/anterior", to: "filas#anterior", as: :filas_anterior
  put "/filas/:id/esvazia_mesa", to: "filas#esvazia_mesa", as: :esvazia_mesa
  get "/filas/:id/shuffle", to: "filas#shuffle", as: :shuffle

  put "/colegiados/:id/proximo", to: "colegiados#proximo", as: :colegiados_proximo
  put "/colegiados/:id/anterior", to: "colegiados#anterior", as: :colegiados_anterior
  put "/colegiados/:id/esvazia_mesa", to: "colegiados#esvazia_mesa", as: :colegiado_esvazia_mesa

  get "/posicao/:matricula", to: "tela#posicao_aluno"

  get "/importar", to: "importer#index"
  post "/importar", to: "importer#import"

  get "/inscricao", to: "inscricao#index"
  post "/inscricao", to: "inscricao#inscrever"

  devise_for :users, controllers: { registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fila.rb
class Fila < ApplicationRecord
  acts_as_list column: :prioridade
  has_many :grupos
  has_many :vagas
  belongs_to :colegiado, required: true

  def vaga_atual
    self.vagas.find_by posicao: self.posicao
  end
  def proxima_vaga
    self.vagas.find_by posicao: self.posicao + 1
  end

  def chama_proximo(mesa_id, incremento=1)
    self.increment!(:posicao, incremento)
    Mesa.associa_vaga_a_mesa(self.vaga_atual, mesa_id)
  end

  def title
    "#{self.codigo}"
  end

  def shuffle
    posicoes = (1..(vagas.size)).to_a.shuffle
    self.vagas.each_with_index do |vaga, i|
      vaga.update(posicao: posicoes[i])
    end
  end
end

app/controllers/filas_controller.rb
class FilasController < ApplicationController
  before_action :set_fila, only: [:show, :edit, :update, :destroy, :anterior, :proximo, :shuffle]
  load_and_authorize_resource

  # GET /filas
  # GET /filas.json
  def index
    @filas = Fila.all
  end

  # GET /filas/1
  # GET /filas/1.json
  def show
    @vaga = @fila.vaga_atual
    @mesa_atual = Mesa.find_by id: session[:mesa]
  end

  # GET /filas/new
  def new
    @fila = Fila.new
  end

  # GET /filas/1/edit
  def edit
  end

  # POST /filas
  # POST /filas.json
  def create
    @fila = Fila.new(fila_params)

    respond_to do |format|
      if @fila.save
        if (@fila.vagas.find_by(posicao: @fila.posicao))
          Mesa.associa_vaga_a_mesa(@fila.vaga, session[:mesa])
          notifica
        end
        format.html { redirect_to @fila, notice: 'Fila was successfully created.' }
        format.json { render :show, status: :created, location: @fila }
      else
        format.html { render :new }
        format.json { render json: @fila.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filas/1
  # PATCH/PUT /filas/1.json
  def update
    respond_to do |format|
      if @fila.update(fila_params)
        format.html { redirect_to @fila, notice: 'Fila was successfully updated.' }
        format.json { render :show, status: :ok, location: @fila }
      else
        format.html { render :edit }
        format.json { render json: @fila.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filas/1
  # DELETE /filas/1.json
  def destroy
    @fila.destroy
    respond_to do |format|
      format.html { redirect_to filas_url, notice: 'Fila was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def shuffle
    authorize! :access, :rails_admin
    @fila.shuffle
    render plain: "Fila reordenada!"
  end

  def anterior
    @fila.chama_proximo(session[:mesa], -1)
    notifica
    redirect_to @fila
  end

  def proximo
    if @fila.posicao == @fila.vagas.count
      Mesa.associa_vaga_a_mesa(nil, session[:mesa])
    else
      @fila.chama_proximo(session[:mesa], 1)
    end
    notifica
    redirect_to @fila
  end

  def esvazia_mesa
    Mesa.associa_vaga_a_mesa(nil, session[:mesa])
    notifica
    redirect_to @fila
  end

  private

    def notifica
      ActionCable.server.broadcast 'telao_notifications_channel', Rodada.dados
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_fila
      @fila = Fila.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fila_params
      params.require(:fila).permit(:codigo, :nome, :prioridade, :ativo, :posicao)
    end
end

app/helpers/filas_helper.rb
module FilasHelper
end

app/views/filas/_form.html.erb
<%= form_with(model: fila, local: true) do |form| %>
  <% if fila.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fila.errors.count, "error") %> prohibited this fila from being saved:</h2>

      <ul>
      <% fila.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :prioridade %>
    <%= form.number_field :prioridade %>
  </div>

  <div class="field">
    <%= form.label :ativo %>
    <%= form.check_box :ativo %>
  </div>

  <div class="field">
    <%= form.label :posicao %>
    <%= form.number_field :posicao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/filas/edit.html.erb
<h1>Editing Fila</h1>

<%= render 'form', fila: @fila %>

<%= link_to 'Show', @fila %> |
<%= link_to 'Back', filas_path %>

app/views/filas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Filas</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Nome</th>
      <th>Prioridade</th>
      <th>Ativo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @filas.each do |fila| %>
      <tr>
        <td><%= fila.codigo %></td>
        <td><%= fila.nome %></td>
        <td><%= fila.prioridade %></td>
        <td><%= fila.ativo %></td>
        <td><%= link_to 'Show', fila %></td>
        <td><%= link_to 'Edit', edit_fila_path(fila) %></td>
        <td><%= link_to 'Destroy', fila, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fila', new_fila_path %>

app/views/filas/new.html.erb
<h1>New Fila</h1>

<%= render 'form', fila: @fila %>

<%= link_to 'Back', filas_path %>

app/views/filas/show.html.erb
<h1>Fila</h1>

<p id="notice"><%= notice %></p>

<p>
  Mesa atual: <b><%= @mesa_atual.nome if @mesa_atual %></b>
</p>


<p>
  <strong>Codigo:</strong>
  <%= @fila.codigo %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @fila.nome %>
</p>

<p>
  <strong>Prioridade:</strong>
  <%= @fila.prioridade %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @fila.ativo %>
</p>

<p>
  <strong>Posição atual:</strong>
  <span style="color: blue;"><%= @fila.posicao %> <%= @fila.vaga_atual&.aluno&.title %></span>
</p>

<p>
  <strong>Próxima posição:</strong>
  <span style="color: #777;"><%= @fila.proxima_vaga&.aluno&.title %></span>
</p>


<div>
  <%= link_to 'Anterior', filas_anterior_path(@fila), method: :put %> |
  <%= link_to 'Próximo', filas_proximo_path(@fila), method: :put %>
</div>

<br>

<div>
  <%= link_to 'Esvazia Mesa', esvazia_mesa_path, method: :put %>
</div>

<br><br>

<%= link_to 'Edit', edit_fila_path(@fila) %> |
<%= link_to 'Back', filas_path %>