config/routes.rb
Rails.application.routes.draw do
  resources :colegiados
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :filas
  resources :mesas
  resources :rodadas
  resources :vagas
  resources :alunos

  root to: "tela#home"
  
  # # Used by e2e tests (in another project):
  # get "/reset", to: "tela#reset", as: :reset
  # get "/cria-cenario", to: "tela#cria_cenario", as: :cria_cenario

  get "/tela", to: "tela#index", as: :tela
  get "/tela/dados", to: "tela#dados", as: :tela_dados
  post "/tela/inscrever", to: "tela#inscrever", as: :tela_inscrever

  post "/mesas/:id/escolher", to: "mesas#escolher", as: :mesa_escolher
  post "/mesas/remover-selecao", to: "mesas#remover_selecao", as: :mesa_remover_selecao

  put "/filas/:id/proximo", to: "filas#proximo", as: :filas_proximo
  put "/filas/:id/anterior", to: "filas#anterior", as: :filas_anterior
  put "/filas/:id/esvazia_mesa", to: "filas#esvazia_mesa", as: :esvazia_mesa
  get "/filas/:id/shuffle", to: "filas#shuffle", as: :shuffle

  put "/colegiados/:id/proximo", to: "colegiados#proximo", as: :colegiados_proximo
  put "/colegiados/:id/anterior", to: "colegiados#anterior", as: :colegiados_anterior
  put "/colegiados/:id/esvazia_mesa", to: "colegiados#esvazia_mesa", as: :colegiado_esvazia_mesa

  get "/posicao/:matricula", to: "tela#posicao_aluno"

  get "/importar", to: "importer#index"
  post "/importar", to: "importer#import"

  get "/inscricao", to: "inscricao#index"
  post "/inscricao", to: "inscricao#inscrever"

  devise_for :users, controllers: { registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  validates_uniqueness_of :matricula
  has_one :mesa
  has_and_belongs_to_many :grupos
  has_many :vagas
  belongs_to :colegiado, required: false

  def esta_em_algum_grupo
    self.grupos.where(ativo: true).order(prioridade: :asc).first != nil
  end

  # def primeiro_grupo_ativo
  #   self.grupos.where(ativo: true).order(prioridade: :asc).first
  # end

  def primeiro_grupo_ativo_com_fila_ativa
    filas = self.grupos\
      .where(ativo: true)\
      .where.not(fila: nil)\
      .order(prioridade: :asc).all
    
    filas_ativas = filas.to_a.select { |f| f.ativo }

    filas_ativas[0]
  end

  # retorna a posição futura mais próxima na fila mais prioritária
  def proxima_vaga
    Fila.where(ativo: true)
        .where(colegiado: self.colegiado)
        .order(prioridade: :asc).each do |fila|
      vagas = fila.vagas.order(posicao: :asc)
        .where(aluno: self)
        .where("posicao >= ?", fila.posicao)
        .limit(1)
      if not vagas.empty?
        vaga = vagas.first
        return vaga    
      end
    end
    
    return nil
  end

  def posicao_total
    vaga = proxima_vaga
    return -1 if not vaga
    return 0 if vaga.posicao == vaga.fila.posicao

    soma = 0
    Fila.where(ativo: true)
        .where(colegiado: self.colegiado)
        .where("prioridade < ?", vaga.fila.prioridade)
        .order(prioridade: :asc).each do |fila|
      diff = fila.vagas.last.posicao - fila.posicao
      soma += diff if diff > 0
    end

    diff = vaga.posicao - vaga.fila.posicao
    soma += diff if diff > 0

    soma
  end

  def inscreve
    if !ativo
      raise "Número de matrícula não encontrado. (Cód. de Erro: 99)"
    end
    if !esta_em_algum_grupo
      raise "Número de matrícula não encontrado. (Cód. de Erro: 42)"
    end
    
    grupo = primeiro_grupo_ativo_com_fila_ativa
    if !grupo
      raise "Matrícula não habilitada para este horário. (Cód. de Erro: 27)"
    end

    # Checa se aluno já está em alguma fila ativa
    vaga = proxima_vaga
    if vaga
      if vaga.posicao == vaga.fila.posicao
        raise "Já está na sua vez!"
      else
        raise "Você já estava na fila (posição: #{vaga.codigo})."
      end
    else
      # Caso contrário, adiciona à fila
      vaga = Vaga.create(aluno: self, fila: grupo.fila)
      InscricaoChannel.inscreve(vaga)
      return { aluno: vaga.aluno, posicao: "#{vaga.codigo}" }
    end
  end

  def title
    "#{self.nome} (#{self.matricula})"
  end
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  
  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:matricula, :nome, :ativo, :score, :fezPreMatricula, :formando)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno, local: true) do |form| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.text_field :matricula %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :ativo %>
    <%= form.check_box :ativo %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score %>
  </div>

  <div class="field">
    <%= form.label :fezPreMatricula %>
    <%= form.check_box :fezPreMatricula %>
  </div>

  <div class="field">
    <%= form.label :formando %>
    <%= form.check_box :formando %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Matricula</th>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.matricula %></td>
        <td><%= aluno.nome %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Matricula:</strong>
  <%= @aluno.matricula %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Ativo?</strong>
  <%= @aluno.ativo %>
</p>

<p>
  <strong>Score:</strong>
  <%= @aluno.score %>
</p>

<p>
  <strong>Fez pré-matrícula?</strong>
  <%= @aluno.fezPreMatricula %>
</p>

<p>
  <strong>É formando?</strong>
  <%= @aluno.formando %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>